name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Yarn
        run: |
          npm install yarn
          yarn install

      - name: Compile Sass file
        run: node_modules/.bin/sass main.scss:main.css

      - name: Make a directory for outputs, move outputs
        run: |
          mkdir output
          mv index.html output
          mv main.css output
          mv images output

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=output --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
